url: https://myfiles.ga
title: myfiles.ga
description: your online place
show_downloads: false
google_analytics: 
theme: jekyll-theme-hacker
timezone: Asia/Calcutta
exclude: [r, p]
keep_files: [keep]
include: [include]
permalink: pretty
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
categories: [pages]
